TrajectoryPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_theta: 0.2
  acc_lim_x: 0.05
  acc_lim_y: 0

  #Set the velocity limits of the robot
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_in_place_vel_theta: 0.3
  max_vel_theta: 0.3
  max_rotational_vel: 0.25

  #Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  holonomic_robot: false

  #The frequency at which the local planner gets called
  controller_frequency: 5.0

  # Whether the *_scale parameters should assume that *_distance are expressed in units of meters
  meter_scoring: true