# The frequency at which the local planner gets called
controller_frequency: 3.0
planner_frequency: 1.0

TrajectoryPlannerROS:
  # Set the acceleration limits of the robot
  acc_lim_theta: 0.15
  acc_lim_x: 0.05
  acc_lim_y: 0

  # Set the velocity limits of the robot
  max_vel_x: 0.15
  min_vel_x: 0.075
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_in_place_vel_theta: 0.15
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  escape_vel: -0.15

  # rotate_recovery
  max_rotational_vel: 0.3
  min_in_place_rotational_vel: 0.2

  # Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  holonomic_robot: false

  # Whether the *_scale parameters should assume that *_distance are expressed in units of meters
  meter_scoring: true

  # Publish the cost grid that the planner will use when planning
  publish_cost_grid_pc: true

  # The amount of time to forward-simulate trajectories in seconds
  sim_time: 4

  # The number of samples to use when exploring the x velocity space
  vx_samples: 10