footprint: [[-0.35, -0.25], [-0.35, 0.25], [0.35, 0.25], [0.35, -0.25]]
#robot_radius: 0.3

obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.05


observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: /laserscan_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: /kinect_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}