#footprint: [[-0.35, -0.22], [-0.35, 0.22], [0.35, 0.22], [0.35, -0.22]]
#robot_radius: 0.3

#obstacle_range: 2.5
#raytrace_range: 3.0
#inflation_radius: 0.03


#observation_sources: point_cloud_sensor

#laser_scan_sensor: {sensor_frame: /laserscan_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: /kinect_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}

plugins:
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  - {name: sonar, type: "range_sensor_layer::RangeSensorLayer"}

inflation_layer:
#  cost_scaling_factor: 0.5
  inflation_radius: 0.03
  footprint: [[-0.35, -0.22], [-0.35, 0.22], [0.35, 0.22], [0.35, -0.22]]

sonar:
  topics: ['/holly/range/front_left', '/holly/range/front_right', '/holly/range/rear']

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 1.6 #1.3
  min_obstacle_height: 0.03
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}

voxel_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 10
  unknown_threshold: 0
  #mark_threshold: 2
  publish_voxel_map: true
  combination_method: 1
  observation_sources: output_points
  output_points:
    data_type: PointCloud2
    topic: /camera/depth/points
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    min_obstacle_height: 0.00
    max_obstacle_height: 3.00
    mark_threshold: 3
    observation_persistence: 2.0