footprint: [[-0.35, -0.22], [-0.35, 0.22], [0.35, 0.22], [0.35, -0.22]]
#robot_radius: 0.3

obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.03


#observation_sources: point_cloud_sensor

#laser_scan_sensor: {sensor_frame: /laserscan_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: /kinect_depth_frame, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}

plugins:
  - {name: sonar, type: "range_sensor_layer::RangeSensorLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}

sonar:
  topics: ['/holly/range/front_left', '/holly/range/front_right', '/holly/range/rear']

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 1.6 #1.3
  min_obstacle_height: 0.03
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}