global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  static_map: true
  resolution: 0.1

  # Specifies the delay in transform (tf) data that is tolerable in seconds.
  transform_tolerance: 1.0


  plugins:
  - {name: static_map,  type: "costmap_2d::StaticLayer"}